//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

import {
  mergeMap as _observableMergeMap,
  catchError as _observableCatch,
} from 'rxjs/operators';
import {
  Observable,
  throwError as _observableThrow,
  of as _observableOf,
} from 'rxjs';
import { Injectable, Inject, InjectionToken } from '@angular/core';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { CheckTokenService } from './check-token.service';
import { environment } from '../src/environments/environment';

export const API_BASE_URL = new InjectionToken<string>('API_BASE_URL');

@Injectable({ providedIn: 'root' })
export class ApiController {
  private http: HttpClient;
  public baseUrl: string = '';
  headers: HttpHeaders | undefined;
  private Token: string = '';
  protected jsonParseReviver: ((key: string, value: any) => any) | undefined =
    undefined;

  constructor(
    @Inject(HttpClient) http: HttpClient,
    private checkTokenService: CheckTokenService
  ) {
    this.http = http;
    //this.baseUrl =  "https://acwade.com/Booking/";
    this.baseUrl = environment.apiUrl;
    this.rebuildHeaders();
  }
  /* getData(): Observable<any> {
    return this.http.get('assets/config.json');
  }
  getbaseUrlData(){
    this.getData().subscribe({
      next: (res) => {
        if (res !== null) {
          // console.log(res.data);
          this.baseUrl = res.apiUrl;
        } else {
          alert('NO DATA For This API URL');
        }
      },
      error: (err) => {
        console.log(err);
      },
    });
   
  }**/
  /**
   * @param body (optional)
   * @return OK
   */
  login(data: any | undefined): Observable<any> {
    data.fireBaseToken = '1234567890';
    return this.http.post<any>(this.baseUrl + 'auth/Auth/Login', data);
  }

  getApi(Url: string | undefined): Observable<any> {
    this.checkTokenService.CheckToken();
    const fullUrl = Url?.startsWith('http') ? Url : this.baseUrl + Url;
    return this.http.get<any>(fullUrl);
  }

  PostApi(data: any | undefined, Url: string | undefined): Observable<any> {
    this.checkTokenService.CheckToken();
    const fullUrl = Url?.startsWith('http') ? Url : this.baseUrl + Url;
    return this.http.post<any>(fullUrl, data);
  }
  PostLiteApi(Url: string | undefined): Observable<any> {
    this.checkTokenService.CheckToken();
    const fullUrl = Url?.startsWith('http') ? Url : this.baseUrl + Url;
    return this.http.post<any>(fullUrl, {});
  }

  private rebuildHeaders() {
    const token = sessionStorage.getItem('token');
    if (token) {
      this.Token = 'Bearer ' + token;
      this.headers = new HttpHeaders({ Authorization: this.Token });
    } else {
      this.headers = undefined;
    }
  }
}
